### ISSUE TITLE
Admin users can not delete/edit polls created by other users

### ISSUE THREAD

**Issue by poVoq** [v1r0x/polls#102]
I think it would be good if users in the "admin" group would be able to see, delete and edit polls, at least the public ones.

**Comment by v1r0x** [comment]
They should definitely not see/edit/delete private polls of other users. Allow editing/deleting public polls is something to think about for a later release. I will add it to the list.

**Comment by joergmschulz** [comment]
NC12 will have an impersonate app - maybe this one resolves this issue.

**Comment by v1r0x** [comment]
Thus the admin could delete all polls of a specific user. But due to the new app it would be impossible to prevent this anyway. I think we should close this issue. It's better to use something which exists instead of implementing something on my own. If you think this is not a good solution please reopen @poVoq
