### ISSUE TITLE
Feature request: anonymous poll

### ISSUE THREAD

**Issue by danielepercivaldi** [v1r0x/polls#38]
I would like an additional option in poll creation: anonymous.
If enabled each one who participates to the poll cannot see the votes of each other but only the totals.

**Comment by v1r0x** [comment]
I'll add this to the list for future development.

**Comment by v1r0x** [comment]
I'll add this to the TODO for the next release, together with #62

**Comment by danielepercivaldi** [comment]
Hi!
It seems that the owner of the poll is able to view all the voting people and the other ones see only the description Partecipent # (french?). Comments are not anonymous.

**Comment by v1r0x** [comment]
Yes, the owner is able to see all participants. All others only see 'Participant X'. Participent is just a typo ;)
Comments are currently not anonymous, because I want to merge #83 first (avoid merge conflicts). If you're - beside non-anonymous - happy with the current PR, I'll merge it and fix non-anonymous commments as soon as #83 has been merged.

**Comment by danielepercivaldi** [comment]
Ok. I'm happy with it.

Thanks.
