### ISSUE TITLE
white background on hover

### ISSUE THREAD

**Issue by v1r0x** [v1r0x/polls#7]
@Liwindo
Pushed to the wrong branch, but could you test if current master fixes the problem with hovering in the poll summary? (see [comment](https://github.com/v1r0x/polls/issues/3#issuecomment-189331921))

**Comment by Liwindo** [comment]
Yeah, it works now. But there are some other problems that I found:

I created a poll with three different days and two time options and activated the time options for all days. The created poll itself looks really strange, because it seems to have duplications. And last but not least I selected 17.30 and 45 and not 16.30 and 45: http://www.directupload.net/file/d/4276/ckuuqxpp_png.htm

**Comment by v1r0x** [comment]
The wrong hour is due to timezones. They are stored in GMT and e.g. germany has GMT+1. Please open a new issue for the duplicates and describe the steps to reproduce it. Thanks for your help!
