### ISSUE TITLE
Style selection 

### ISSUE THREAD

**Issue by bodo1987** [v1r0x/polls#72]
Hi everyone,

I recently suggested a different style (#69) which was according to myself and all other peoples that I showed it to, a clearer one than the current default. Apparently, v1r0x didn't like it and he closed the PR very quickly. 
First of all, I would like to ask v1r0x to don't close PRs to fast. The originator should always have the option to defend the idea and maybe it can be changed in a way that it is more acceptable. 
However, styles are always subjective. Of course, it is possible that somebody likes more the simple, approach which little details and other like more a bit elaborated design. My suggestion would therefore be, that I try to add different styles to app!
I'm not totally sure how to do it, but probably I would introduce a settings menu where you can choose between different styles. By default, it would stay the same that it is at the moment. An admin can choose alternative ones, depended from the css style files available on the server. I haven’t done any work on this yet, but I think it would not be too complicate. A modification like this would increase the maintenance effort if the html templates will be changed in future, but in my opinion it is not worse than the language files. Also they have to be updated all the time for each modification.
Before I start working on this, I would like to hear what the others are thinking about this idea. I want to avoid that the PR is closed again very quickly and my work would be worthless. 

Cheers,
Bodo

**Comment by v1r0x** [comment]
Hi Bodo,

first of all: I really appreciate any help!
But if a PR or any other help doesn't seem to improve anything or is something I don't like or think is nothing I wanted the app to be, I'll close it.
In your case I didn't see the need for UI modifications and IMHO your changes were less clean and nice than the current one. Thus I decided to close the PR. If you think this was rude or too fast or anything else I think you can easily reopen it and discuss this with me. And if I still don't like your changes you can clone the project and release it yourself. It's free software.

Back to this PR:
I'm a fan of settings and let the user modify the app to match their needs. But in the case of owncloud they want something else: Define good defaults which suits most of the users. Since this is the philosophy of owncloud I don't want to break this with any (unnecessary) settings.
What I could offer you is to start a new repo called something like "polls-styles" which can be downloaded and replace the original css file. I'll then add an info to the app page in the appstore with a link to your repo.

**Comment by v1r0x** [comment]
I'll close this for now, since there hasn't been any feedback. If you want to answer or re-open it: Feel free to do so!
